# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba01d011706045397c5f125469f54e14e0631fc50339e1dfd26e931562993670105208f8dd5b46ef8c341681364a99afcc928a4f4e65eb12b5745e367b1afa79

test:
  secret_key_base: e303ea9b2e389dae8bc2890f7ac121f377eeff97accc60a33eed506c46a9444cd8e6e38f381c9b85bf51e2095d7ddcd06d896624ef93dd46921e434c0243a318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
